### ISSUE TITLE
TypeError: Class constructor Entity cannot be invoked without 'new'

### ISSUE THREAD

**Issue by chris-runn** [AbyxBelgium/TypeScriptRestMapper#2]
It's a great package. Thanks!
I tested the sample codes in my project and I had some error in "target: es5 in tsconfig".
"target: es6" is working.

Chrome console error message
> TypeError: Class constructor Entity cannot be invoked without 'new'
    at new Post (RestMapper.ts?21ee:3)
    at Service.parseObject (bundle.js?9650:4017)
    at Service.eval (bundle.js?9650:4008)
    at Generator.next (<anonymous>)
    at fulfilled (bundle.js?9650:3981)

I have to run it in "target: es5".
Any idea? or need more info?

**Comment by pverscha** [comment]
Hi Chriss,

Thanks for reaching out! I'll try to compile the package as an ES5 target tonight. I'll come back to you if this is fixed.

**Comment by chris-runn** [comment]
Hi, @pverscha.
Thanks and I'm waiting :)

**Comment by pverscha** [comment]
Hi Chris,

I've added a Babel-transpiler step which transpiles the code to ES5. Can you try again? https://www.npmjs.com/package/typescript-rest-mapper

**Comment by pverscha** [comment]
Ok, I made some more changes. ES5 is now the default (you just need to update to version 1.0.24 or higher), but ES6 can be selected if desired.

**Comment by chris-runn** [comment]
I changed to version 1.0.24 and it's working by ES5. Very good! Thanks :)

**Comment by pverscha** [comment]
Thanks! :) I'm marking this as fixed
